### ISSUE TITLE
断点续传有点问题

### ISSUE THREAD

**Issue by frozleaf** [scanfing/HttpFileServer#4]
// 文件
https://github.com/scanfing/HttpFileServer/blob/main/src/HttpFileServer/Handlers/HttpGetHandler.cs

/// <summary>
/// 断点续传响应支持
/// </summary>
/// <returns></returns>
protected async Task ResponseContentPartial(string path, HttpListenerRequest request, HttpListenerResponse response, bool onlyHead = false)
{
    ...
    response.AddHeader("Content-Range", $"bytes {range.Item1}-{range.Item2}/{stream.Length}");

    var buff = new byte[81920];
    var rangeEnd = range.Item2 > range.Item1 ? range.Item2 : stream.Length - 1;
    // 此处应该为
    // var bytesNeeds = rangeEnd + 1 - range.Item1;
    var bytesNeeds = rangeEnd - range.Item1;
    ...
}

**Comment by scanfing** [comment]
谢谢
